version: '3.1'

  comments:
    image: registry.tobisyurt.net/comments
    container_name: comments-webapp
    restart: always
    ports:
      - 8071:8080
    depends_on:
      - mongo
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
    environment:
      # SPRING_PROFILES_ACTIVE=prod --> not needed
      IP_BLOCK_TIME: 900
      QUIZ_COUNT: 5
      QUIZ_VALIDITY_SECONDS: 120
      QUIZ_COMPLEXITY: 2
      ADMIN_NAME: the_bloggers_name
      SPRING_SECURITY_USER_NAME: user
      SPRING_SECURITY_USER_PASSWORD: PleaseChangeMe
