# Use root/example as user/password credentials
version: '3.1'

volumes:
  mongo_data:

services:
  mongo:
    image: mongo
    restart: always
    volumes:
      - mongo_data:/data/db
  #    environment:
  #      MONGO_INITDB_ROOT_USERNAME: root
  #      MONGO_INITDB_ROOT_PASSWORD: example

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8082:8081
    depends_on:
      - mongo
  #    environment:
  #      ME_CONFIG_MONGODB_ADMINUSERNAME: root
  #      ME_CONFIG_MONGODB_ADMINPASSWORD: example
  #      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/

  comments:
    image: registry.tobisyurt.net/comments
    restart: always
    ports:
      - 8071:8080
    depends_on:
      - mongo
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
    environment:
      # SPRING_PROFILES_ACTIVE=prod --> not needed
      IP_BLOCK_TIME: 60
      QUIZ_COUNT: 3
      QUIZ_VALIDITY_SECONDS: 120
      QUIZ_COMPLEXITY: 2
      SPRING_DATA_MONGODB_HOST: mongo
      SPRING_DATA_MONGODB_DATABASE: comments
