version: '3.1'

volumes:
  mongo_data:

services:
  mongo:
    image: mongo
    restart: always
    # only for dev environments needed, because your dev server will run outside the stack's network...
    ports:
    - 27018:27017
    volumes:
      - mongo_data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: PleaseChangeMe

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8083:8081
    depends_on:
      - mongo
    environment:
      ME_CONFIG_BASICAUTH_USERNAME: tobi
      ME_CONFIG_BASICAUTH_PASSWORD: tester
      ME_CONFIG_MONGODB_URL: mongodb://root:PleaseChangeMe@mongo:27017/

